### ISSUE TITLE
a problem for replay

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#22]
The replay does work properly.

```
(ophyd)xf11id@xf11id-ws3:~$ replay
Qt: Session management error: None of the authentication protocols specified are supported
/home/xf11id/Repos/dataportal/dataportal/broker/simple_broker.py:343: UserWarning: A RunStop record could not be found for the run with run_start_uid 41ccb59b-c91c-425b-8cc1-035474c21778
  warnings.warn(error_msg)
/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py:210: MatplotlibDeprecationWarning: This class has been deprecated in 1.4 as it has no additional functionality over `NavigationToolbar2QT`.  Please change your code to use `NavigationToolbar2QT` instead
  mplDeprecation)
/nfs/xf11id/mc/envs/ophyd/lib/python2.7/site-packages/enaml/qt/docking/dock_manager.py:184: DockLayoutWarning: child SplitLayout has same orientation as parent
  DockLayoutValidator(available)(layout)
Traceback (most recent call last):
  File "/nfs/xf11id/mc/envs/ophyd/bin/replay", line 9, in <module>
    load_entry_point('replay==0.0.0.dev0', 'console_scripts', 'replay')()
  File "/home/xf11id/Repos/replay/replay/replay.py", line 176, in main
    ui.muxer_model.header = db[-1]
  File "/home/xf11id/Repos/replay/replay/muxer/model.py", line 211, in _run_header_changed
    self.dataframe = self.data_muxer.to_sparse_dataframe()
  File "/home/xf11id/Repos/replay/replay/scalar/model.py", line 320, in new_dataframe
    self.dataframe = changed['value']
  File "/home/xf11id/Repos/replay/replay/scalar/model.py", line 325, in dataframe_changed
    self.new_data()
  File "/home/xf11id/Repos/replay/replay/scalar/model.py", line 335, in new_data
    if self.dataframe[col].dropna().values[0].shape == tuple()]

AttributeError: 'Timestamp' object has no attribute 'shape'
(ophyd)xf11id@xf11id-ws3:~$ 

```

**Comment by ericdill** [comment]
I resolved this issue with @yugangzhang the same day that this issue was reported.  

The rest of this response is for perpetuity. The original problem is that pandas is not respecting time zones. The `pd.to_datetime function`, in particular, is the culprit (https://github.com/NSLS-II/dataportal/blob/master/dataportal/muxer/data_muxer.py#L481).  After sending data through the data_muxer, the resulting pandas dataframe has timezones that are at UTC time, not NSLS-II time (-4/-5 hours depending on daylight savings time or not).  If you pass it a timezone aware value then it converts it into UTC time.  @tacaswell and I tried to fix this problem with the following code: https://github.com/ericdill/dataportal/commit/4dad2f176dd7db33919bf237a79f7f41265c2106. However, that caused the above stack trace because the new implementation of `_maybe_convert_times` returned a `Timezone` object, which `replay` didn't know what to do with.  The implementation in master (linked above) returns numpy.datetime64 objects. Yes, numpy has its own implementation of datetime... who knew??  Anyway, we rolled back the update that @tacaswell and I made and now replay works. But the times are wrong and still need to be dealt with.  Frigging timezones...

**Comment by ericdill** [comment]
cc @danielballan (timezones, what a mess!)

**Comment by danielballan** [comment]
Can you work on making sure that replay doesn't completely crash in the
event of time confusion while I look at this?

**Comment by ericdill** [comment]
That replay bug came from a hack-y fix implemented by @tacaswell and I.  That hacky fix has been rolled back, so replay does not encounter this issue any longer.  That being said, turns out that the fix in https://github.com/NSLS-II/replay/pull/27/files#diff-0e57b8a190f04076975b81d2aebdb867R340 will catch that error, but then replay can't plot data versus time :disappointed:
