### ISSUE TITLE
jupyter directory with one user instance

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/Bug-Reports#52]
![jupyterfilesystem_xf23id1](https://cloud.githubusercontent.com/assets/13630233/10975807/b2b5ed10-83b6-11e5-91c0-c1b5f8e2aa45.png)
![jupyterterminal_xf23id1_vs_xf23idhome_vthampyhome](https://cloud.githubusercontent.com/assets/13630233/10975809/b49be166-83b6-11e5-8e58-4d41d35c2f61.png)

Jupyter isn't linking to the appropriate home directory in the front page where you select the notebooks you want to use.  The ssh terminal window is appropriately linked. Google chrome cache cleared and restarted before reproducing.  Used two different workstations.

**Comment by danielballan** [comment]
I think this is a "won't fix." The beamline accounts are set up in an unusual way, and in the medium-term I think they will be eliminated entirely. I can help set up alternative ways to share notebooks between user accounts.

**Comment by ambarb** [comment]
@danielballan:  That is appreciated.  Formerly, it seemed only those with root access could create user accounts.  RE the issue here: I think there are open questions on my part on how to proceed.  To provide background: @cmazzoli and I were not aware that 23id1 shouldn't be used in this way as we thought this was at the beamline's discretion. We were going to rely on the "beamline notebook" for user support of users that want to use their own code at their home institution (current week's users are applicable here).  For our current users, I preemptively set in motion VPN access and followed that by contacting Mizuki for jupyter accounts.  Then we would be ready if the users changed their mind and I could verify that these requests were reasonable.  It would be excellent to know how to proceed, i.e., Do all users need python notebook accounts or only if they want remote access? @danielballan do I correctly understand that you are indicating beamline staff will create the accounts?  Should we give the team one notebook account (i.e. the PI) or all team members an account? Does the former create issues with VPN which should be on an individual basis? What is the policy on this and who decides beamlines or data/network systems?

Also, I have a related question and would like to hear the input/suggestions. Should I be able to do the following:

 I can't see other people directories in the notebook terminal. If i know (or guess correctly) the user name, then I can list that user's directory and copy whatever I like.  Since our user base has thus far mostly been limited to BNL based users or users that want to process their own data, I am not sure if it is because the groups are common or if is because of my beamline user status or if this is true across the board.

**Comment by danielballan** [comment]
There is no policy, and ultimately the policy won't come from me.

I would advocate for all users receiving a VPN account and a controls account as part of their accepted beam time proposal. Then all users could have access to their data and our analysis software via jupyterhub and the data broker. I hope that the administrators can streamline the process as much as possible so that it is not left up to beamline scientists to handle this. Of course, we can only make this automatic up to a point: first-time users will need to clear cybersecurity training.

Group accounts do not meet the lab's legal requirements. There needs to be a single person accountable for a given username. This is why the beamline accounts like xf23id1 do not have ssh access. However, we could manage access to data and/or scripts on group-wise basis. There are even plans to make jupyter notebooks editable by many people simultaneously, as in Google docs.

In the short term, these are my recommendations:
1. Strongly encourage all users to get VPN accounts _and_ email Mizuki to get controls accounts, even if they aren't interested in remote access.
2. Work with me to streamline the process distributing shared "beamline notebooks" so that everyone has copies they can see and use. We have a couple ideas about how this could work. We can start with something simple for now.

As to the freewheeling copying from others' directories, I think everyone can do that, but I'm not sure if the situation will also be so insecure.

**Comment by ericdill** [comment]
@ambarb The reason why you cannot see other users home directories is a technical one.  Each users home directory is mounted "on demand" which occurs on the first access to it.  If the user whose home directory you are trying to access has not logged in to the machine that you are currently on then you will not be able to see their home directory if you try to `ls` the `/home` directory.  However, if you guess correctly and cd to that users home directory it will then be mounted because you are trying to access it and you can then see it.

**Comment by ambarb** [comment]
I bring up this second point not because I think I should be able to see other directories or wonder why.  I bring it up because if a person wanted to invest the time they could surf the server for other people's code (i.e. code an outside user developed that they are not willing to share)

**Comment by danielballan** [comment]
I agree. It's been convenient in this early stage, but it might be getting
time to lock things down. Ask Mizuki.

**Comment by ambarb** [comment]
Re: @danielballan points.  Cybersecurity training is required user access training before they can begin experiments.

**Comment by danielballan** [comment]
Oh, great. Then proposing "jupyterhub for all" is not actually adding any new roadblocks for the users.

**Comment by ambarb** [comment]
Here is the link to the user guide.
https://www.bnl.gov/ps/userguide/

Currently, there is no information about any of these data systems.  The operating account is for monetary funds.

**Comment by danielballan** [comment]
So, action on this issue will be adding to the documentation to explain how we are expecting users to use jupyterhub, including the current process for obtaining the necessary accounts. Sound OK, @ambarb?

**Comment by heroux** [comment]
This is an issue that is being resolve with Paul Zschack and a small technical group. THey met last friday and will continue working on that.

All users  need to have  cybersecurity training .

They all will have their account and have access to only  data associated with their PASS proposal.

+++++++++++++++++++++++++++
Energy Sciences Directorate/Photon Science Division, Bldg 745 L107
Brookhaven National Laboratory
Upton, NY 11973, USA
Phone office:  631 344 4454

**Comment by danielballan** [comment]
nbexamples has begun to address notebook-sharing.  Everything else here was discussion, so I am closing this issue.
